blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blogapp.urls')),
    # path('blog/', include('blogapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from home import views as v

urlpatterns = [
    path('', views.index, name='index'),
    path('post_view/<int:id>', views.post_view, name='post_view'),
    path('search_data', views.search_data, name='search_data'),
    path('signup', v.handle_signup,name='signup'),
    path('comment/<int:postid>', views.post_comment,name='comment'),
    path('post_view/logout', v.handle_logout),
    path('reply/<int:postid>/<int:sno>', views.handle_reply, name='reply'),
    path('delete/<int:rid>/<int:pid>', views.delete_rply,name='delete'),
    path('delete_comment/<int:cid>/<int:pid>', views.delete_comment,name='delete_comment'),
    path('write_blog',views.create_blog,name='create_blog'),
    path('save_blog',views.save_blog,name='save_blog')
   
]

blogapp/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User
from django.utils.timezone import now
# Create your models here.
class post(models.Model):
    post_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=20)
    content = models.TextField()
    Timestamp = models.DateField(auto_now_add=True)
   
    
    def __str__(self):
        return self.title + '(' + str(self.post_id) + ')'
    
class comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    comment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_post = models.ForeignKey(post, on_delete=models.CASCADE)
    
    timestamp = models.DateField(default=now)
    
    def __str__(self):
        return self.comment + '('+ str(self.comment_id)+ ')'
    
class comment_reply(models.Model):
    rply_id = models.AutoField(primary_key=True)
    rply = models.TextField()
    comment_sno = models.IntegerField(max_length=3, default=0)
    comment = models.ForeignKey(comment, on_delete=models.CASCADE)
    user =  models.ForeignKey(User, on_delete=models.CASCADE)
    rply_post = models.ForeignKey(post, on_delete=models.CASCADE)
    timestamp = models.DateField(default=now)
    
    def __str__(self):
        return str(self.comment) + "(" +self.rply+ ')' + str(self.rply_id)

blogapp/views.py
from django.db.models import query
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .models import post, comment, comment_reply
from django.contrib.auth.models import User
from django.contrib import messages

# Create your views here.
def index(request):
    post_data = post.objects.all()
    return render(request, 'blogapp/blog.html',{'post':post_data})


def post_view(request,id):
    post_view_data = post.objects.filter(post_id = id)
    load_comment = comment.objects.filter(comment_post=id)
    reply_data = comment_reply.objects.filter(rply_post=id)
    comments_length = len(reply_data)+len(load_comment)
    return render(request, 'blogapp/post_view.html',{'post':post_view_data,'load_comment':load_comment,'reply':reply_data,'comments_length':comments_length})

def search_data(request):
    query = request.GET.get('search')
    print(query)
    print('working')
    datatemp = post.objects.all()
    data = []
    search = False
    
    for item in datatemp:
        if query in item.title.lower() or query in item.h1heading.lower() or query in item.h1content.lower() or query in item.h2heading.lower() or query in item.h2content.lower():
            data.append(item)
            search = True
        elif query =='':
            data.append(item)
        
           
    return render(request, 'blogapp/blog.html',{'post':data,'txt_query':query,'search':search})

def post_comment(request, postid):
    if request.method == 'POST':
        print('working')
        comment_text = request.POST['comment']
        user = request.user
        post_id = post.objects.get(post_id=postid)
        comment_data = comment(comment=comment_text, user=user, comment_post=post_id)
        comment_data.save()
        messages.success(request,'Your comment has been posted successfully')      
        return HttpResponse(post_view(request,postid))

    
def handle_reply(request, postid, sno):
    
    if request.method == 'POST':
        rply = request.POST['rply']
        user = request.user
        post_id = post.objects.get(post_id=postid)
        on_comment = comment.objects.get(comment_id = sno)
        reply_data = comment_reply(rply = rply,comment_sno=sno, user= user, comment=on_comment, rply_post=post_id)
        reply_data.save()   
        messages.success(request,'Your rply has been posted successfully')
    return redirect('/blog/post_view/'+str(postid))   
    
def delete_rply(request, rid,pid):
    reply_data = comment_reply.objects.get(rply_id = rid)
    reply_data.delete()
    messages.success(request,'Your comment has been deleted successfully')
    return redirect('/blog/post_view/'+str(pid)) 

def delete_comment(request, cid, pid):
    comment_data = comment.objects.get(comment_id = cid)
    comment_data.delete()
    messages.success(request,'Your comment has been deleted successfully')
    return redirect('/blog/post_view/'+str(pid)) 

def create_blog(request):

    return render(request,'blogapp/create_blog.html')


def save_blog(request):
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        post_data= post(title=title, content=content)
        post_data.save()
        print(content)
        return render(request,'blogapp/blog.html')

templates/blogapp/blog.html
{% extends 'base.html' %}
{% block blog %}active{% endblock %}

{% block title %}Blog{% endblock %}


{% block body %}
<style>
  .button{
    text-align: center;
    margin-bottom: 100px;
  }
</style>


{% if txt_query %}
  <div>
    <h3  style="font-family: 'Merriweather', serif;margin: 20px;color:rgb(0, 0, 0) ">Search result:\ <span style="color:red">{{txt_query}}</span></h3>
  </div>
{% if post|length < 1 %}

<div style="margin-left:200px" >

  <ul style="font-style: italic;
  font-size: 25px;">
    <li>Result not found.</li>
    <li>Try a Specific keywords.</li>
  </ul>
  
</div>
{% endif %}

{% endif %}


<div style="margin: auto;" class="container my-3">
  <div class="row mb-2">
{% if post|length > 0 %}
  

    <div>
      <h1 style="font-family: 'Merriweather', serif;">Featured Posts</h1>
    </div>
    {% endif %}

      {% for item in post %}
  
  
      <div class="container">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <strong  style="font-family: 'Merriweather', serif;"class="d-inline-block mb-2 text-primary">{{item.title}}</strong>
  
            <div class="mb-1 text-muted">{{item.Timestamp}}</div>
            <!-- <div  style="font-family: 'Merriweather', serif;"> {{item.content|safe|truncatechars:100}}</div> -->
            
           <div> <a style="width: 149px;
            margin-top: 10px;" href="/blog/post_view/{{item.post_id}}" class="btn btn-primary" >Continue reading</a>
          </div>
          </div>
    
        </div>
      </div>
  
      {% endfor %}
    </div>
  </div>
  <div class="button">
    <a href="/blog/write_blog"  class="btn btn-info">Create Blog</a>
  </div>
{% endblock %}

{% block script %}
<script>
  
{% if run %}
  document.getElementById('search').nodeValue = '';
{% endif %}  


</script> 
{% endblock %}

{% block footer %}
<div style="height:50px;display:flex;justify-content:center;align-items:center; position:fixed" class="footerr bg-dark">
  <span style="font-weight: bolder;" >© Designed By Maaz Khan, Inc</span>
</div>
{% endblock %}

templates/blogapp/create_blog.html
{% extends 'base.html' %}
{% block nav %}
  
{% endblock %}

{% block title %}Blog{% endblock %}

{% block body %}
    
<style>
    .container{
        margin: auto;
    
        margin-top: 30px;
        margin-bottom: 200px;
    }
    .tox{
        border-radius: 4px;

box-shadow: 0px 0px 3px;
margin-bottom: 18px;
    }
    input{
        width: 300px;
        margin-bottom: 18px;
    }
</style>

<div class="container">
    <form action="/blog/save_blog" method="post"> {% csrf_token %}

        <div class="col-sm-10">
            <input name="title" type="text" class="form-control" id="inputPassword" placeholder="Blog Title">
        </div>
        <div class="col-sm-10">
            <textarea name="simple_text" id="text" hidden cols="30" rows="10"></textarea>
        </div>
        <textarea hidden name="" id="id_content" cols="30" rows="10"></textarea>
        <textarea name="content" id="content" hidden cols="30" rows="10"></textarea>
        <button id="click" type="submit" class="btn btn-success">Success</button>
        <div id="temp" hidden></div>
    </form>
</div>

{% endblock %}

{% block script %}
<script>
    $(document).ready(function()
    {

        var script= document.createElement('script');
        script.type='text/javascript';
        script.src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js";
        document.head.appendChild(script);
        
        script.onload=function(){
        tinymce.init({
            selector: "#id_content",
            height:500,
            width:1000,
            plugins: [
                'advlist autolink link image lists charmap print preview hr anchor pagebreak',
                'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
                'table emoticons template paste help'
              ],
              toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | ' +
                'bullist numlist outdent indent | link image | print preview media fullpage | ' +
                'forecolor backcolor emoticons | help',
              menu: {
                favs: {title: 'My Favorites', items: 'code visualaid | searchreplace | emoticons'}
              },
              menubar: 'favs file edit view insert format tools table help',
              content_css: 'css/content.css'
            });
        }
    })
    var value = document.getElementById('content')
    
    $('#click').click(function()
    {
        console.log('working')
        let val = tinymce.get('id_content').getContent();
        var text = {{val|safe}}
        
        value.value = val
        console.log(text)
        
      


    })
</script> 
{% endblock %}

templates/blogapp/post_view.html
{% extends "base.html" %}
{% block blog %}active{% endblock  %}
{% block title %} Post_view {% endblock %}
{% block blogout %} <a  class="dropdown-item" href="/blog/post_view/logout">Log out</a>{% endblock  %}
{% block body %}




<div style="text-align:start; margin-top: 53px;" class="container">
    <div style="margin-bottom: 50px;" class="container">
        <h1 style="font-family: 'Merriweather', serif;" class="fw-light">{{post.0.title}}</h1>
        <h5 style="font-family: 'Merriweather', serif;color:blue" class="fw-light">{{post.0.Timestamp}}</h5>
        <hr>
        <div>
            {{post.0.content|safe}}
        </div>
        <hr>
        <div>
            <h1>Comments ({{comments_length}})</h1>
        </div>
        {% if user.is_authenticated %}
        <div style="    border:1px solid;border-left-color: currentcolor;
        padding: 10px;
        border-radius: 8px;
        border-color: rgb(71, 70, 70);" class="mb-3">

  
<form method="post" action="/blog/comment/{{post.0.post_id}}"> {% csrf_token %}
    
    <label for="exampleFormControlInput1" class="form-label">Post a comment.</label>
    <input name="comment" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Enter your comment">
    <button type="submit" class="btn btn-primary my-2">Post</button>
</form>
</div>{% load static %}
{% endif %}

{% for comment in load_comment  %}
  
<!-- comment here -->
<div style="margin: 10px;" class="row">
    <div style="width: 75px;
    margin-top: 7px;" class="col-md-2 " >
        <img style="margin: auto;
        width: 51px;
        padding-top: 10px;" src="{% static 'blogapp/user.svg' %}" alt="">
    </div>
    <div class="col-md-10" >
        <span style="font-weight: bold;" >{{comment.user}}</span>
        <span style="font-size: 10px;border-radius: 21px;
        height: 16px;" class="badge bg-secondary">{{comment.timestamp}}</span> <br>
        <span>{{comment.comment}}</span> <br>
        {% if user.is_authenticated %}
        <a style="width: 54px;
        height: 23px;
        font-size: 14px;
        text-align: center;
        padding: 1px; font-weight:bold" class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample{{comment.comment_id}}" role="button" aria-expanded="false" aria-controls="collapseExample{{comment.comment_id}}">
            Reply
          </a>
          {% if comment.user == request.user %}          
          <form style="display: inline;" action="/blog/delete_comment/{{comment.comment_id}}/{{post.0.post_id}}" method="post"> {% csrf_token %}
            
            <button style="width: 54px;
            height: 23px;
            font-size: 14px;
            text-align: center;
            padding: 1px; font-weight:bold" type="submit" class="btn btn-danger my-2">Delete</button>
        </form>
        {% endif %}

          <div class="collapse" id="collapseExample{{comment.comment_id}}">
            <div style="margin-top: 8px;" class="card card-body">
                <div  >
            <form action="/blog/reply/{{post.0.post_id}}/{{comment.comment_id}}" method="post"> {% csrf_token %}

                <label for="exampleFormControlInput{{comment.comment_id}}" class="form-label">Reply a comment.</label>
                <input style="height: 28px;" name="rply" type="text" class="form-control" id="exampleFormControlInput{{comment.comment_id}}" placeholder="Enter your comment">
                <button style="width: 54px;
                height: 23px;
                font-size: 14px;
                text-align: center;
                padding: 1px; font-weight:bold" type="submit" class="btn btn-primary my-2">Post</button>
          </form>
                </div>
            </div>
          </div>
  
        
        {% endif %}

       
        
    </div>
 

</div>


{% for replies in reply  %}
{% if replies.comment_sno == comment.comment_id %}

<div class="reply">
    <div style="margin: 10px; margin-left: 99px;" class="row">
        <div style="width: 75px;
        margin-top: 7px;" class="col-md-2 " >
            <img style="margin: auto;
            width: 51px;
            padding-top: 10px;" src="{% static 'blogapp/user.svg' %}" alt="">
        </div>
        <div class="col-md-10" >
            <span style="font-weight: bold;" >{{replies.user}}</span>
            <span style="font-size: 10px;border-radius: 21px;
            height: 16px;" class="badge bg-secondary">{{replies.timestamp}}</span> <br>
            <span>{{replies.rply}}</span> <br>
        </form>

        {% if user.is_authenticated %}
          
        {% if replies.user == request.user %}
          
        
        <form action="/blog/delete/{{replies.rply_id}}/{{post.0.post_id}}" method="post"> {% csrf_token %}
            
            <button style="width: 54px;
            height: 23px;
            font-size: 14px;
            text-align: center;
            padding: 1px; font-weight:bold" type="submit" class="btn btn-danger my-2">Delete</button>
        </form>
        {% endif %}
        {% endif %}
        
</div>
</div>
 

</div>
{% endif %}
{% endfor %}


{% endfor %}

    </div>
 
   
</div>



{% endblock %}